{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "First So Yummy Team`s backend",
    "description": "Showing off swagger-ui-express",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json", "multipart/form-data"],
  "produces": ["application/json"],
  "servers": [{ "url": "https://soyummy-backend-first-team.onrender.com" }],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Subscribe",
      "description": "Subscribtion email"
    },
    {
      "name": "Recipes",
      "description": "Everything about Recipes"
    },
    {
      "name": "Ingredients",
      "description": "Everything about Ingredients"
    },
    {
      "name": "Favorite recipes",
      "description": "Find, remove and add favorite recipes"
    },
    {
      "name": "Popular recipes",
      "description": "Find popular recipes"
    },
    {
      "name": "Own recipe",
      "description": "Everything about your recipes"
    },
    {
      "name": "Shopping list",
      "description": "Everything about your shopping list"
    },
    {
      "name": "Modal",
      "description": "Find information about user"
    }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Email should be unique",
            "content": {}
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Email or password is incorrect",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          }
        }
      }
    },
    "/auth/current": {
      "get": {
        "tags": ["Auth"],
        "summary": "Return current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": " Token expired, please Login again.",
            "content": {}
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "Users` logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": "No Content"
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/recipes/category-list": {
      "get": {
        "tags": ["Recipes"],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryListResponse"
                }
              }
            }
          },

          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/recipes/main-page": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Find 4 recipes in 4 categories (Breakfast, Miscellaneous, Chicken, Dessert)",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipeResponse"
                }
              }
            }
          },

          "404": {
            "description": "Recipe not found",
            "content": {}
          }
        }
      }
    },
    "/recipes/{category}": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Receiving 8 recipes of the selected category",
        "parameters": [
          {
            "name": "category",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "Name of category",
            "example": "Beef"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Amount recipes on page"
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Number of page"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryResponse"
                }
              }
            }
          },

          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/recipes/id/{id}": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Find recipe by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "Id of recipe",
            "example": "640cd5ac2d9fecf12e889864"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipeResponse"
                }
              }
            }
          },

          "400": {
            "description": "Invalid recipe id",
            "content": {}
          },

          "404": {
            "description": "Recipe not found",
            "content": {}
          }
        }
      }
    },
    "/ingredients/list": {
      "get": {
        "tags": ["Ingredients"],
        "summary": "Find list of ingredients",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IngredientResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ingredients list",
            "content": {}
          }
        }
      }
    },
    "/ingredients": {
      "get": {
        "tags": ["Ingredients"],
        "summary": "Find recipes for search ingredient",
        "parameters": [
          {
            "name": "search",
            "in": "query",
            "required": true,
            "type": "string",
            "example": "Challots"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipeResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request ingredient",
            "content": {}
          },
          "404": {
            "description": "Not found ingredient or not found recipe",
            "content": {}
          }
        }
      }
    },
    "/favorite": {
      "post": {
        "tags": ["Favorite recipes"],
        "summary": "Add recipe to favorite",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Id of recipe",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FavoriteResponse"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": "Added to favorite"
          }
        }
      },
      "get": {
        "tags": ["Favorite recipes"],
        "summary": "Get favorite recipes",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipeResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Favorite recipes"],
        "summary": "Delete recipe from favorite",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Id of recipe",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FavoriteRequest"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Successful operation"
          }
        }
      }
    },
    "/popular-recipe": {
      "get": {
        "tags": ["Popular recipes"],
        "summary": "Find recipes for search ingredient",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ModalResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found popular recipes",
            "content": {}
          }
        }
      }
    },
    "/search": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Find recipes for title",
        "parameters": [
          {
            "name": "search",
            "in": "query",
            "required": true,
            "type": "string",
            "example": "Beef"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipeResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {}
          },
          "404": {
            "description": "Not found recipe",
            "content": {}
          }
        }
      }
    },
    "/modal": {
      "get": {
        "tags": ["Modal"],
        "summary": "Find information about user, how days he is loged, how many has own recupes and how many recipes adds to favorite",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ModalResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized, or Token expired, please Login again, or Invalid token, or Email or password is incorrect",
            "content": {}
          }
        }
      }
    },
    "/shopping-list": {
      "get": {
        "tags": ["Shopping list"],
        "summary": "Find all ingredients from shopping list",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetShoppingListResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Shopping list"],
        "summary": "Add ingredient to shopping list",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Ingredient object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ShoppingListRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PostShoppingListResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Shopping list"],
        "summary": "Delete ingredient from shopping list",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Ingredient object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ShoppingListIdRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PostShoppingListResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/subscribe": {
      "get": {
        "tags": ["Subscribe"],
        "summary": "Send hello mail",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {}
          }
        }
      },
      "post": {
        "tags": ["Shopping list"],
        "summary": "Add ingredient to shopping list",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Ingredient object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ShoppingListRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PostShoppingListResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Shopping list"],
        "summary": "Delete ingredient from shopping list",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Ingredient object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ShoppingListIdRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PostShoppingListResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "username", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "username": {
            "type": "string",
            "description": "User's name",
            "example": "Andrew"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "string",
              "description": "User's id",
              "example": "32143232436545474"
            },
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "username": {
              "type": "string",
              "description": "User's name",
              "example": "Andrew"
            },
            "avatarURL": {
              "type": "string",
              "description": "Link to user`s avatar url",
              "example": "//www.gravatar.com/b58996c504c5638798eb6b511e6f49af"
            }
          },
          "example": [
            {
              "resUser": {
                "_id": "6443d47d40e926b3c1d9755c",
                "username": "Andrew",
                "email": "user@example.com",
                "avatarURL": "//www.gravatar.com/avatar/b58996c504c5638798eb6b511e6f49af"
              }
            }
          ]
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "resUser": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "number",
                  "description": "User's id",
                  "example": "32143232436545474"
                },
                "email": {
                  "type": "string",
                  "description": "User's email",
                  "format": "email"
                },
                "username": {
                  "type": "string",
                  "description": "User's name",
                  "example": "Andrew"
                },
                "avatarURL": {
                  "type": "string",
                  "description": "Link to user`s avatar url",
                  "example": "//www.gravatar.com/b58996c504c5638798eb6b511e6f49af"
                }
              }
            },

            "token": {
              "type": "number",
              "example": "32143232436545474"
            }
          },
          "example": {
            "resUser": {
              "_id": "6443e37ad6feaf6e0cbafd41",
              "username": "Andrew",
              "email": "user2@example.com",
              "avatarURL": "//www.gravatar.com/avatar/ab53a2911ddf9b4817ac01ddcd3d975f"
            },
            "token": "eyJhbGcNiIsInR5.eyJpZCI6IjYhZDmUwY2JhZmQIjoidXZXhhbXBsZS5jb20iLCJpYXQiOjE2ODIxODg0NzAsImV4cCI6MTY4MjI3MTI3MH0.mM8DVmEcs_UOeEu_DKTPtWyvMEnDhT3oXbIx6A1PbBY"
          }
        }
      },
      "CategoryListResponse": {
        "type": "array",
        "items": {
          "type": "string",
          "properties": {
            "description": "Category`s name"
          },
          "example": ["Beef", "Vegan"]
        }
      },
      "CategoryResponse": {
        "type": "object",
        "items": {
          "type": "string",
          "properties": {
            "total": {
              "type": "string",
              "description": "Count of recepes in category",
              "example": "45"
            },
            "recipesList": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "String",
                  "description": "Recipe title"
                },
                "category": {
                  "type": "String",
                  "description": "Recipe category"
                },
                "area": {
                  "type": "String",
                  "description": "Recipe country"
                },
                "instructions": {
                  "type": "String",
                  "description": "Instruction of recipe"
                },
                "description": {
                  "type": "String",
                  "description": "Recipe description"
                },
                "thumb": {
                  "type": "String",
                  "description": "Recipe photo"
                },
                "preview": {
                  "type": "String",
                  "description": "Recipe photo preview"
                },
                "time": {
                  "type": "String",
                  "description": "Recipe preparation time"
                },
                "youtube": {
                  "type": "String",
                  "description": "Recipe cooking video"
                },
                "tags": {
                  "type": "Array",
                  "description": "Array of recipe tags"
                },
                "createdAt": "Recept created time",
                "updatedAt": "Recept updated time",
                "ingredients": {
                  "type": [
                    {
                      "ingredientId": {
                        "type": "Schema.Types.ObjectId",
                        "description": "Ingredient's id"
                      },
                      "measure": {
                        "type": "String",
                        "description": "Ingredient's measure ibn recipe"
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "example": {
          "total": 43,
          "recipesList": [
            {
              "_id": "640cd5ac2d9f",
              "title": "Irish stew",
              "category": "Beef",
              "area": "Irish",
              "instructions": "Heat the oven to 180C/350F/gas mark 4...",
              "description": "A traditional Irish dish made with lamb...",
              "thumb": "https://images/media/meals/sxxpst1468569714.jpg",
              "preview": "https://res.cloudinary.com//image/kknfjaqupiqhufj5kspx.jpg",
              "time": "160",
              "youtube": "https://www.youtube.com/",
              "tags": ["Stew", "Meat"],
              "createdAt": "2023-03-11T19:25:33.240Z",
              "updatedAt": "2023-04-14T20:02:28.085Z",
              "ingredients": [
                {
                  "_id": "643e78d78a15223d43a979ba",
                  "id": "640c2dd963a319ea671e3796",
                  "measure": ["300g soaked overnight in water"]
                },
                {
                  "_id": "643e78d78a15223d43a979bb",
                  "id": "640c2dd963a319ea671e370c",
                  "measure": ["2kg cut into 3cm cubes"]
                }
              ]
            }
          ]
        }
      },
      "RecipeResponse": {
        "type": "object",
        "items": {
          "type": "string",
          "properties": {
            "title": {
              "type": "String",
              "description": "Recipe title"
            },
            "category": {
              "type": "String",
              "description": "Recipe category"
            },
            "area": {
              "type": "String",
              "description": "Recipe country"
            },
            "instructions": {
              "type": "String",
              "description": "Instruction of recipe"
            },
            "description": {
              "type": "String",
              "description": "Recipe description"
            },
            "thumb": {
              "type": "String",
              "description": "Recipe photo"
            },
            "preview": {
              "type": "String",
              "description": "Recipe photo preview"
            },
            "time": {
              "type": "String",
              "description": "Recipe preparation time"
            },
            "youtube": {
              "type": "String",
              "description": "Recipe cooking video"
            },
            "tags": {
              "type": "Array",
              "description": "Array of recipe tags"
            },
            "createdAt": "Recept created time",
            "updatedAt": "Recept updated time",
            "ingredients": {
              "type": [
                {
                  "ingredientId": {
                    "type": "Schema.Types.ObjectId",
                    "description": "Ingredient's id"
                  },
                  "measure": {
                    "type": "String",
                    "description": "Ingredient's measure ibn recipe"
                  }
                }
              ]
            }
          }
        },
        "example": {
          "recipe": [
            {
              "_id": "640cd5ac2d9f",
              "title": "Irish stew",
              "category": "Beef",
              "area": "Irish",
              "instructions": "Heat the oven to 180C/350F/gas mark 4...",
              "description": "A traditional Irish dish made with lamb...",
              "thumb": "https://images/media/meals/sxxpst1468569714.jpg",
              "preview": "https://res.cloudinary.com//image/kknfjaqupiqhufj5kspx.jpg",
              "time": "160",
              "youtube": "https://www.youtube.com/",
              "tags": ["Stew", "Meat"],
              "createdAt": "2023-03-11T19:25:33.240Z",
              "updatedAt": "2023-04-14T20:02:28.085Z",
              "ingredients": [
                {
                  "_id": "643e78d78a15223d43a979ba",
                  "id": "640c2dd963a319ea671e3796",
                  "measure": ["300g soaked overnight in water"]
                },
                {
                  "_id": "643e78d78a15223d43a979bb",
                  "id": "640c2dd963a319ea671e370c",
                  "measure": ["2kg cut into 3cm cubes"]
                }
              ]
            }
          ]
        }
      },
      "IngredientResponse": {
        "type": "object",
        "ingredientList": {
          "properties": {
            "_id": {
              "type": "Schema.Types.ObjectId",
              "description": "Ingredient's id"
            },
            "ttl": {
              "type": "String",
              "description": "Ingredient's title"
            },

            "desc": {
              "type": "String",
              "description": "Ingredient's description"
            },
            "t": {
              "type": "String",
              "description": "Type of ingredients"
            },

            "thb": {
              "type": "String",
              "description": "Ingredient's photo"
            }
          }
        },
        "example": {
          "ingredientList": [
            {
              "_id": "640c2dd963a319ea671e368c",
              "ttl": "Challots",
              "desc": "A type of onion that has a mild, sweet flavor and a distinctive bulb shape, often used in French cuisine to add flavor to sauces, dressings, and other dishes.",
              "t": "",
              "thb": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678564674/ovlvnvcuzttiplnzewm3.png"
            },
            {
              "_id": "640c2dd963a319ea671e3668",
              "ttl": "Basil Leaves",
              "desc": "Basil, also called great basil, is a culinary herb of the family Lamiaceae (mints).\r\n",
              "t": "",
              "thb": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678564216/c8mwndz8kbgb29wjn4eg.png"
            }
          ]
        }
      },
      "FavoriteResponse": {
        "type": "object",
        "required": ["recipeId"],
        "properties": {
          "recipeId": {
            "type": "string",
            "description": "Recipe`s id",
            "example": "640cd5ac2d9fecf12e889864"
          }
        }
      },
      "ModalResponse": {
        "type": "array",
        "items": {
          "type": "number",
          "properties": {
            "amoutOwnRecipes": {
              "type": "number",
              "description": "How many recipes user add to own recipes",
              "example": "0"
            },
            "amoutFavoriteRecipes": {
              "type": "number",
              "description": "How many recipes user add to favorite recipes",
              "example": "0"
            },
            "days": {
              "type": "number",
              "description": "How many days user is in aplication",
              "example": "0"
            }
          },
          "example": [
            {
              "amoutOwnRecipes": 2,
              "amoutFavoriteRecipes": 4,
              "days": 1
            }
          ]
        }
      },
      "ShoppingListRequest": {
        "type": "object",
        "required": ["ingredientId", "measure"],
        "properties": {
          "ingredientId": {
            "type": "string",
            "description": "ingredient id",
            "example": "640c2dd963a319ea671e374f"
          },
          "measure": {
            "type": "string",
            "description": "Ingredient measure",
            "example": "200g"
          }
        }
      },
      "ShoppingListIdRequest": {
        "type": "object",
        "required": ["ingredientId", "measure"],
        "properties": {
          "ingredientId": {
            "type": "string",
            "description": "ingredient id",
            "example": "640c2dd963a319ea671e374f"
          }
        }
      },
      "PostShoppingListResponse": {
        "type": "object",
        "items": {
          "properties": {
            "ingredientId": {
              "type": "Schema.Types.ObjectId",
              "description": "Ingredient's id in ingredient`s db"
            },
            "measure": {
              "type": "String",
              "description": "Ingredient's measure"
            },
            "_id": {
              "type": "Schema.Types.ObjectId",
              "description": "Ingredient's id in shopping-list"
            }
          },
          "example": [
            {
              "ingredientId": "640c2dd963a319ea671e374f",
              "measure": ["20 g"],
              "_id": "6442e7d3a93c8d3629c3be3c"
            }
          ]
        }
      },
      "GetShoppingListResponse": {
        "type": "object",
        "items": {
          "properties": {
            "id": {
              "type": "Schema.Types.ObjectId",
              "description": "Ingredient's id in shopping-list"
            },
            "measure": {
              "type": "String",
              "description": "Ingredient's measure"
            },
            "ingredient": {
              "type": "object",
              "items": {
                "properties": {
                  "_id": {
                    "type": "Schema.Types.ObjectId",
                    "description": "Ingredient's id in ingredient`s db"
                  },
                  "ttl": {
                    "type": "String",
                    "description": "Ingredient's title"
                  },

                  "desc": {
                    "type": "String",
                    "description": "Ingredient's description"
                  },
                  "t": {
                    "type": "String",
                    "description": "Type of ingredients"
                  },

                  "thb": {
                    "type": "String",
                    "description": "Ingredient's photo"
                  }
                }
              }
            }
          },
          "example": [
            {
              "id": "6442e7d3a93c8d3629c3be3c",
              "measure": ["20 g"],
              "ingredient": {
                "_id": "640c2dd963a319ea671e374f",
                "ttl": "Red Pepper",
                "desc": "A sweet and crunchy vegetable that is often used in cooking and is a good source of vitamins A and C. It is also known as a bell pepper or capsicum.",
                "t": "",
                "thb": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678564916/shxhx8z19qqsm3xb52kv.png"
              }
            }
          ]
        }
      },
      "securitySchemes": {
        "Bearer": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT"
        }
      }
    }
  }
}
